### PR TITLE
Corrected leap seconds table for 2016 and added entry for 2017

### PR DESCRIPTION
**Pull request by ArneBachmann**
Second attempt for PR.

### CODE REVIEW

**Comment by ArneBachmann** [comment]
Reason for the test changes is that its datetime objects refert to the year 2016 who's leap seconds I modified.

**Comment by ArneBachmann** [comment]
@pingswept Would you mind merging this PR? Or is there anything missing?

**Comment by amkellett** [comment]
Hi, the latest version of Pysolar I just cloned has an incorrect leap second entry for 2016 (I think).  Instead
of:
`(+1, 0), # 2016`
I think it should be:
`(0, +1), # 2016`

I know I had to change my leap second settings for GNSS processing in July 2015, and last NewYear's Eve. 
I am very new, so I'm not doing the pull request thing.  Hope to be out of newbie stage soon. Thanks

**Comment by ArneBachmann** [comment]
Yes, this is exactly what was I did in my PR #60 , also added the source to it:
htps://www.nist.gov/pml/time-and-frequency-division/atomic-standards/leap-second-and-ut1-utc-information

**Comment by pingswept** [comment]
@amkellett Yes, I believe @ArneBachmann is correct. If you saw the old leap second entry, you are very likely using an old version, or cloning the repository incorrectly, or something like that.

**Pull request merged**
