### PR TITLE
Augment leap seconds table and added data source for that

### PR DESCRIPTION
**Pull request by ArneBachmann**

### CODE REVIEW

**Comment by ArneBachmann** [comment]
Fixes #56

**Comment by pingswept** [comment]
Hi Arne,

Your patch looks decent, but your pull request should be against the master branch, rather than the dev branch. The latter is just experimental. (Sorry, that's probably a bit confusing, but I've occasionally needed a place to divert people who want to make big changes.)

Brandon

**Comment by pingswept** [comment]
Oh, also, it looks like the build tests are failing for Python 3. Please investigate that if you have the time.

**Comment by ArneBachmann** [comment]
Well my changes build and test without problems, but this pull request has received a lot of other commits from other people, I'd blame them for breaking the tests. Let me create a new separate PR.

**Comment by ArneBachmann** [comment]
@pingswept Would you mind merging this PR? Or is there anything missing?

**Comment by ArneBachmann** [comment]
The new PR is #60.

**Pull request closed without merging**
