### PR TITLE
Add leap second for 2016

### PR DESCRIPTION
**Pull request by moosebert**
Add leap second to 2016 per [IERS Bulletin C](https://hpiers.obspm.fr/iers/bul/bulc/bulletinc.dat), published July 6th 2016.

### CODE REVIEW

**Comment by pingswept** [comment]
Awesome, thanks!

**Comment by DouglasAllen** [comment]
Hasn't there been another since December? 
https://www.timeanddate.com/time/leap-seconds-future.html

**Comment by moosebert** [comment]
Not since the one published July 6th, and observed December 31st of 2016 (that I'm aware of).  Note for the above URL, should have been https://hpiers.obspm.fr/iers/bul/bulc/bulletinc.52 (which I've corrected now).

**Comment by DouglasAllen** [comment]
That's just that I used to be a general but now I'm an expert. hi hi

**Comment by DouglasAllen** [comment]
http://maia.usno.navy.mil/ser7/tai-utc.dat

**Comment by DouglasAllen** [comment]
K. Who want's to do this one?
ftp://maia.usno.navy.mil/ser7/deltat.data

**Comment by DouglasAllen** [comment]
I have a copy of this if anyone id interested. I'm no scientist just a collector of junk.
https://github.com/DouglasAllen/C-lib-Novas

**Pull request merged**
